In [2]:
import torch

In [3]:
x = torch.empty(5, 3)
print(type(x))
x

<class 'torch.Tensor'>


tensor([[4.7359e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00,        nan, 0.0000e+00],
        [7.3470e+28, 6.1425e+28, 7.1441e+31],
        [6.9987e+22, 7.8675e+34, 4.7418e+30],
        [5.9663e-02, 7.0374e+22, 0.0000e+00]])

In [4]:
tensor_ones = torch.ones(2,3)
print(tensor_ones)
tensor_zeros =  torch.zeros(2,3)
tensor_zeros

tensor([[1., 1., 1.],
        [1., 1., 1.]])


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
print(tensor_zeros.dtype)
tensor_zeros_int = torch.zeros(2,3,dtype=torch.long)
tensor_zeros_int.dtype

torch.float32


torch.int64

In [6]:
x = torch.rand(5,3)
x

tensor([[0.3640, 0.9737, 0.3698],
        [0.6653, 0.2733, 0.8518],
        [0.3154, 0.4318, 0.3452],
        [0.8414, 0.7911, 0.3519],
        [0.8516, 0.5288, 0.1024]])

In [7]:
x_size = x.size()
print(x_size)

row, col = x_size
row,col

torch.Size([5, 3])


(5, 3)

In [8]:
torch.arange(1,10,1)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
y = torch.rand(5, 3)
z1 = x + y
print(z1)
z2 = torch.add(x, y)
print(z2)
z3 = torch.empty(5, 3)
torch.add(x, y, out=z3)
print(z3)
y.add_(x)
print(y)  




tensor([[1.2287, 1.5638, 0.8689],
        [0.7202, 1.2671, 0.8708],
        [1.2410, 1.3796, 1.1709],
        [1.6806, 0.8074, 0.8743],
        [0.9783, 1.4148, 0.1113]])
tensor([[1.2287, 1.5638, 0.8689],
        [0.7202, 1.2671, 0.8708],
        [1.2410, 1.3796, 1.1709],
        [1.6806, 0.8074, 0.8743],
        [0.9783, 1.4148, 0.1113]])
tensor([[1.2287, 1.5638, 0.8689],
        [0.7202, 1.2671, 0.8708],
        [1.2410, 1.3796, 1.1709],
        [1.6806, 0.8074, 0.8743],
        [0.9783, 1.4148, 0.1113]])
tensor([[1.2287, 1.5638, 0.8689],
        [0.7202, 1.2671, 0.8708],
        [1.2410, 1.3796, 1.1709],
        [1.6806, 0.8074, 0.8743],
        [0.9783, 1.4148, 0.1113]])


In [10]:
a =torch.randn(2,3)
print(a)
b =torch.randn(2,3)
print(b)

c =torch.sub(a, b)
print(c)
d =torch.mul(a, b)
print(d)
e =torch.div(a, b)
print(e)



tensor([[-0.8832,  0.6757, -1.2201],
        [ 0.0288,  0.5482,  0.1299]])
tensor([[-1.6309,  0.0462, -0.5324],
        [ 1.6109,  1.0119, -1.0236]])
tensor([[ 0.7477,  0.6294, -0.6877],
        [-1.5820, -0.4637,  1.1536]])
tensor([[ 1.4405,  0.0312,  0.6496],
        [ 0.0464,  0.5548, -0.1330]])
tensor([[ 0.5415, 14.6100,  2.2915],
        [ 0.0179,  0.5418, -0.1269]])


In [11]:
a =torch.randn(2, 3)
print(a)
b =torch.randn(3, 2)
print(b)
c =torch.mm(a, b)
print(c)


tensor([[ 0.1790, -0.5927, -0.7099],
        [-0.6463, -0.3751,  0.8342]])
tensor([[ 0.2025, -0.5948],
        [-0.1957, -0.0921],
        [-0.5173,  1.2785]])
tensor([[ 0.5195, -0.9595],
        [-0.4890,  1.4855]])


In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 1)   # 使用-1时pytorch将会自动根据其他维度进行推导
print(x.size(), y.size(), z.size()) 

torch.Size([4, 4]) torch.Size([16]) torch.Size([16, 1])


In [13]:
x = torch.randn(2, 3)
print(x)
x_cat_dim0 = torch.cat((x,x,x), dim=0)
x_cat_dim1 = torch.cat((x,x,x), dim=1)
print(x_cat_dim0)
print(x_cat_dim1)


tensor([[ 0.5539, -0.5983,  0.2298],
        [-0.3793, -0.0207,  0.4211]])
tensor([[ 0.5539, -0.5983,  0.2298],
        [-0.3793, -0.0207,  0.4211],
        [ 0.5539, -0.5983,  0.2298],
        [-0.3793, -0.0207,  0.4211],
        [ 0.5539, -0.5983,  0.2298],
        [-0.3793, -0.0207,  0.4211]])
tensor([[ 0.5539, -0.5983,  0.2298,  0.5539, -0.5983,  0.2298,  0.5539, -0.5983,
          0.2298],
        [-0.3793, -0.0207,  0.4211, -0.3793, -0.0207,  0.4211, -0.3793, -0.0207,
          0.4211]])


In [14]:
x = torch.randn(1)
print(x)
print(x.size())
print(x.item())
print(type(x.item())) 

tensor([0.1882])
torch.Size([1])
0.1881554126739502
<class 'float'>


In [15]:
a =torch.randn(2,3)
print(a)
b =torch.clamp(a, -0.5, 0.5)
print(b)

tensor([[ 0.5492, -1.1300, -0.8314],
        [-1.5408,  0.3635, -0.6417]])
tensor([[ 0.5000, -0.5000, -0.5000],
        [-0.5000,  0.3635, -0.5000]])


In [16]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [17]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b) 


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
