In [1]:
import torch, torchvision
model = torchvision.models.resnet18(weights=None)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)
prediction = model(data)
print(prediction)
loss = (prediction - labels).sum()
loss.backward()
optim = torch.optim.SGD(model.parameters(),lr = 1e-2,momentum=0.9)
optim

tensor([[[[0.0850, 0.2071, 0.2219,  ..., 0.6493, 0.5922, 0.8848],
          [0.4933, 0.5660, 0.7358,  ..., 0.8768, 0.9203, 0.4817],
          [0.6965, 0.9377, 0.9109,  ..., 0.8964, 0.8153, 0.9237],
          ...,
          [0.8258, 0.3853, 0.7499,  ..., 0.8175, 0.6370, 0.5304],
          [0.5803, 0.9142, 0.6131,  ..., 0.4417, 0.4227, 0.4646],
          [0.4125, 0.8116, 0.8709,  ..., 0.0872, 0.5669, 0.2634]],

         [[0.6527, 0.4130, 0.8657,  ..., 0.2878, 0.8836, 0.2088],
          [0.2967, 0.9642, 0.4806,  ..., 0.0764, 0.4028, 0.9576],
          [0.5657, 0.1708, 0.6048,  ..., 0.6484, 0.5511, 0.7538],
          ...,
          [0.1229, 0.9346, 0.9477,  ..., 0.2143, 0.4147, 0.4707],
          [0.5484, 0.9408, 0.0401,  ..., 0.3646, 0.4481, 0.0204],
          [0.1728, 0.2444, 0.9035,  ..., 0.8606, 0.4129, 0.1001]],

         [[0.1986, 0.4653, 0.6670,  ..., 0.9375, 0.6391, 0.7020],
          [0.0632, 0.1057, 0.9346,  ..., 0.7525, 0.7355, 0.2842],
          [0.1749, 0.4003, 0.8580,  ..., 0

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0.9
    nesterov: False
    weight_decay: 0
)

In [2]:
import torch
x1 = torch.ones((2,2))
x1

tensor([[1., 1.],
        [1., 1.]])

In [3]:
x2 = torch.ones((2,2),requires_grad=True)
x2

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y2 = x2 + 1
y2.requires_grad

True

In [21]:
a = torch.tensor([2.],requires_grad= True)
b = torch.tensor([4.],requires_grad= True)
y = a**2 + 2*b**3
y.backward()
a.grad,b.grad

(tensor([4.]), None)

(tensor([4.]), tensor([96.]))